apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: notime-page-tls
spec:
    secretName: notime-page
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: notime.page
    dnsNames:
        - notime.page
        - www.notime.page
    acme:
        config:
            - http01:
                ingressClass: nginx
            domains:
                - notime.page
                - www.notime.page